# Generated by Django 3.2.5 on 2021-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_genre_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a genre of the book on russian', max_length=50, null=True),
        ),
    ]
