# Generated by Django 3.2.5 on 2021-08-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_genres_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
    ]
