# Generated by Django 3.2.5 on 2021-08-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_genre_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_src',
            field=models.URLField(help_text='Enter an url for the source of description', null=True),
        ),
    ]
