# Generated by Django 3.2.5 on 2021-08-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_book_cover_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_src',
            field=models.URLField(blank=True, help_text='Enter an url for the source of cover', null=True),
        ),
    ]
